package com.axz.model;

import java.util.Date;

public class NewsComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.comment_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.news_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Integer newsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.user_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.reply_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Integer replyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.parent_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.createtime
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.approve
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Integer approve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.disapprove
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private Integer disapprove;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_comment.content
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.comment_id
     *
     * @return the value of news_comment.comment_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.comment_id
     *
     * @param commentId the value for news_comment.comment_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.news_id
     *
     * @return the value of news_comment.news_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Integer getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.news_id
     *
     * @param newsId the value for news_comment.news_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setNewsId(Integer newsId) {
        this.newsId = newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.user_id
     *
     * @return the value of news_comment.user_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.user_id
     *
     * @param userId the value for news_comment.user_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.reply_id
     *
     * @return the value of news_comment.reply_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Integer getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.reply_id
     *
     * @param replyId the value for news_comment.reply_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setReplyId(Integer replyId) {
        this.replyId = replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.parent_id
     *
     * @return the value of news_comment.parent_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.parent_id
     *
     * @param parentId the value for news_comment.parent_id
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.createtime
     *
     * @return the value of news_comment.createtime
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.createtime
     *
     * @param createtime the value for news_comment.createtime
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.approve
     *
     * @return the value of news_comment.approve
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Integer getApprove() {
        return approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.approve
     *
     * @param approve the value for news_comment.approve
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setApprove(Integer approve) {
        this.approve = approve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.disapprove
     *
     * @return the value of news_comment.disapprove
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public Integer getDisapprove() {
        return disapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.disapprove
     *
     * @param disapprove the value for news_comment.disapprove
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setDisapprove(Integer disapprove) {
        this.disapprove = disapprove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_comment.content
     *
     * @return the value of news_comment.content
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_comment.content
     *
     * @param content the value for news_comment.content
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}