package com.axz.mapper;

import com.axz.model.GetNews;
import com.axz.model.GetNewsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GetNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    long countByExample(GetNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int deleteByExample(GetNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int deleteByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int insert(GetNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int insertSelective(GetNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    List<GetNews> selectByExampleWithBLOBs(GetNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    List<GetNews> selectByExample(GetNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    GetNews selectByPrimaryKey(Integer newsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") GetNews record, @Param("example") GetNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") GetNews record, @Param("example") GetNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByExample(@Param("record") GetNews record, @Param("example") GetNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByPrimaryKeySelective(GetNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(GetNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table get_news
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByPrimaryKey(GetNews record);
}