package com.axz.mapper;

import com.axz.model.NewsComment;
import com.axz.model.NewsCommentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface NewsCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    long countByExample(NewsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int deleteByExample(NewsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int insert(NewsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int insertSelective(NewsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    List<NewsComment> selectByExample(NewsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    NewsComment selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") NewsComment record, @Param("example") NewsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByExample(@Param("record") NewsComment record, @Param("example") NewsCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByPrimaryKeySelective(NewsComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_comment
     *
     * @mbg.generated Thu Jan 02 14:30:58 CST 2020
     */
    int updateByPrimaryKey(NewsComment record);
}